[general]
import = [
	"~/.config/alacritty/catppuccin-latte.toml",
	# "~/.config/alacritty/catppuccin-mocha.toml",
]

[window]
decorations = "None"
option_as_alt = "OnlyLeft"

[scrolling]
history = 0

[font]
normal = { style = "Regular", family = "MesloLGL Nerd Font" }
italic = { style = "Italic", family = "MesloLGL Nerd Font" }
bold = { style = "Bold", family = "MesloLGL Nerd Font" }
bold_italic = { style = "Bold Italic", family = "MesloLGL Nerd Font" }

size = 14
offset = { y = -4 }
glyph_offset = { y = -1 }

builtin_box_drawing = false

[keyboard]
bindings = [
	# applenotes://showNote?identifier=19C0DA4D-7B19-4179-A189-3724532D0CC4
	{ key = "Enter", mods = "Shift", chars = "\u001b[13;2u" },
]
